//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.AutoEnt.Portal.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIS.AutoEnt.Portal.GlobalResources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password 的本地化字符串。
        /// </summary>
        public static string Login_EmptyPasswordWarning {
            get {
                return ResourceManager.GetString("Login_EmptyPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your user name 的本地化字符串。
        /// </summary>
        public static string Login_EmptyUserNameWarning {
            get {
                return ResourceManager.GetString("Login_EmptyUserNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgot Password 的本地化字符串。
        /// </summary>
        public static string Login_ForgotPwd {
            get {
                return ResourceManager.GetString("Login_ForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login_Login {
            get {
                return ResourceManager.GetString("Login_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed 的本地化字符串。
        /// </summary>
        public static string Login_LoginFailed {
            get {
                return ResourceManager.GetString("Login_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Name 的本地化字符串。
        /// </summary>
        public static string Login_RememberName {
            get {
                return ResourceManager.GetString("Login_RememberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Password 的本地化字符串。
        /// </summary>
        public static string Login_RememberPwd {
            get {
                return ResourceManager.GetString("Login_RememberPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        public static string Login_SignOut {
            get {
                return ResourceManager.GetString("Login_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Account 的本地化字符串。
        /// </summary>
        public static string Login_YourAccount {
            get {
                return ResourceManager.GetString("Login_YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Setting 的本地化字符串。
        /// </summary>
        public static string My_AccountSetting {
            get {
                return ResourceManager.GetString("My_AccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Home 的本地化字符串。
        /// </summary>
        public static string My_Home {
            get {
                return ResourceManager.GetString("My_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Setting 的本地化字符串。
        /// </summary>
        public static string My_Setting {
            get {
                return ResourceManager.GetString("My_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Workbench 的本地化字符串。
        /// </summary>
        public static string My_Workbench {
            get {
                return ResourceManager.GetString("My_Workbench", resourceCulture);
            }
        }
    }
}
