//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.AutoEnt.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PISFrameworkEntities : DbContext
    {
        public PISFrameworkEntities()
            : base("name=PISFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OrgFunction> OrgFunctions { get; set; }
        public DbSet<OrgGroup> OrgGroups { get; set; }
        public DbSet<OrgRole> OrgRoles { get; set; }
        public DbSet<OrgUser> OrgUsers { get; set; }
        public DbSet<SysFile> SysFiles { get; set; }
        public DbSet<SysFolder> SysFolders { get; set; }
        public DbSet<SysMessage> SysMessages { get; set; }
        public DbSet<SysMetadata> SysMetadatas { get; set; }
        public DbSet<SysModule> SysModules { get; set; }
        public DbSet<SysObject> SysObjects { get; set; }
        public DbSet<SysRegistry> SysRegistries { get; set; }
        public DbSet<SysDataStructure> SysDataStructures { get; set; }
        public DbSet<SysAuth> SysAuths { get; set; }
    }
}
