//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.AutoEnt.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysDataStructure
    {
        public System.Guid Id { get; set; }
        public System.Guid ObjectId { get; set; }
        public string StructureCode { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> PathLevel { get; set; }
        public string Path { get; set; }
        public Nullable<bool> IsLeaf { get; set; }
    }
}
