//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.AutoEnt.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMetadata
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DomainId { get; set; }
        public System.Guid ObjectId { get; set; }
        public string ObjectCode { get; set; }
        public string CNumber { get; set; }
        public int OwnerType { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public int SecurityLevel { get; set; }
        public Nullable<int> Version { get; set; }
        public string XMetaTag { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public string DefStructureCode { get; set; }
    }
}
