//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS.AutoEnt.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMessage
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string SysType { get; set; }
        public string Catalog { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public Nullable<int> Important { get; set; }
        public string MessageChain { get; set; }
        public string Attachments { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public string Tag { get; set; }
        public System.Guid MetadataId { get; set; }
    }
}
